export const SEED_NEGOCIOS = [
  {
    id: 'seed-1',
    nombre: 'Tacos Don Luis',
    categoria: 'Comida',
    descripcion: 'Los mejores tacos de carne asada y burritos del Centro Histórico de Durango. Tradición familiar desde 1985 con recetas originales.',
    horario: 'Lunes a Sábado, 8:00 AM - 10:00 PM',
    direccion: 'Calle Constitución 234, Centro Histórico, Durango',
    productos: ['Tacos de asada', 'Burritos', 'Quesadillas', 'Aguas frescas', 'Gringas'],
    lat: 24.0226,
    lng: -104.6578,
    telefono: '618-123-4567',
    imagen: null,
    creadoEn: '2026-06-06T10:00:00Z',
  },
  {
    id: 'seed-2',
    nombre: 'Café La Molienda',
    categoria: 'Cafetería',
    descripcion: 'Cafetería artesanal con el mejor café de olla de Durango. Ambiente acogedor con pan recién horneado cada mañana.',
    horario: 'Lunes a Domingo, 7:00 AM - 9:00 PM',
    direccion: 'Av. 20 de Noviembre 456, Zona Centro, Durango',
    productos: ['Café de olla', 'Cappuccino', 'Pan artesanal', 'Molletes', 'Chocolate caliente'],
    lat: 24.0198,
    lng: -104.6553,
    telefono: '618-234-5678',
    imagen: null,
    creadoEn: '2026-06-06T10:05:00Z',
  },
  {
    id: 'seed-3',
    nombre: 'Artesanías Doña Lupita',
    categoria: 'Artesanías',
    descripcion: 'Artesanías huicholas auténticas, textiles bordados a mano y joyería tradicional duranguense. Piezas únicas directas de artesanos locales.',
    horario: 'Lunes a Sábado, 9:00 AM - 7:00 PM',
    direccion: 'Mercado Gómez Palacio, Local 15, Durango',
    productos: ['Artesanías huichol', 'Textiles bordados', 'Joyería de plata', 'Figuras de madera', 'Bolsas tejidas'],
    lat: 24.0245,
    lng: -104.6612,
    telefono: '618-345-6789',
    imagen: null,
    creadoEn: '2026-06-06T10:10:00Z',
  },
  {
    id: 'seed-4',
    nombre: 'Gorditas La Abuela',
    categoria: 'Comida',
    descripcion: 'Gorditas de horno y caldillo duranguense como los hacía la abuela. Comida casera con sazón tradicional del estado.',
    horario: 'Martes a Domingo, 8:00 AM - 4:00 PM',
    direccion: 'Calle Zarco 128, Barrio de Analco, Durango',
    productos: ['Gorditas de horno', 'Caldillo duranguense', 'Enchiladas', 'Tamales', 'Pozole rojo'],
    lat: 24.0180,
    lng: -104.6530,
    telefono: '618-456-7890',
    imagen: null,
    creadoEn: '2026-06-06T10:15:00Z',
  },
  {
    id: 'seed-5',
    nombre: 'Mezcalería El Alacrán',
    categoria: 'Bar/Bebidas',
    descripcion: 'Bar artesanal especializado en mezcal y sotol duranguense. Catas y experiencias con destilados de la región Sierra.',
    horario: 'Miércoles a Sábado, 6:00 PM - 1:00 AM',
    direccion: 'Calle Bruno Martínez 312, Centro, Durango',
    productos: ['Mezcal artesanal', 'Sotol duranguense', 'Cócteles de mezcal', 'Tabla de quesos', 'Cata de mezcales'],
    lat: 24.0215,
    lng: -104.6595,
    telefono: '618-567-8901',
    imagen: null,
    creadoEn: '2026-06-06T10:20:00Z',
  },
  {
    id: 'seed-6',
    nombre: 'Panadería San José',
    categoria: 'Panadería',
    descripcion: 'Panadería tradicional con más de 40 años. Conchas, polvorones y pan de muerto que son patrimonio del barrio.',
    horario: 'Lunes a Domingo, 6:00 AM - 9:00 PM',
    direccion: 'Calle Pino Suárez 89, Barrio de Tierra Blanca, Durango',
    productos: ['Conchas', 'Polvorones', 'Bolillos', 'Cuernos', 'Pan de muerto'],
    lat: 24.0160,
    lng: -104.6640,
    telefono: '618-678-9012',
    imagen: null,
    creadoEn: '2026-06-06T10:25:00Z',
  },
  {
    id: 'seed-7',
    nombre: 'Barbería El Clásico',
    categoria: 'Servicios',
    descripcion: 'Barbería de estilo clásico con servicio premium. Cortes modernos, arreglo de barba y afeitado con navaja caliente.',
    horario: 'Lunes a Sábado, 9:00 AM - 8:00 PM',
    direccion: 'Av. Normal 567, Col. Guadalupe, Durango',
    productos: ['Corte clásico', 'Arreglo de barba', 'Afeitado con navaja', 'Corte y barba combo', 'Tratamiento capilar'],
    lat: 24.0280,
    lng: -104.6510,
    telefono: '618-789-0123',
    imagen: null,
    creadoEn: '2026-06-06T10:30:00Z',
  },
  {
    id: 'seed-8',
    nombre: 'Florería Primavera',
    categoria: 'Comercio',
    descripcion: 'Arreglos florales únicos para toda ocasión. Flores frescas de invernadero local, plantas de ornato y regalos artesanales.',
    horario: 'Lunes a Sábado, 8:00 AM - 7:00 PM; Domingo, 9:00 AM - 2:00 PM',
    direccion: 'Calle Victoria 178, Centro, Durango',
    productos: ['Arreglos florales', 'Ramos de novia', 'Plantas de ornato', 'Coronas fúnebres', 'Centros de mesa'],
    lat: 24.0202,
    lng: -104.6565,
    telefono: '618-890-1234',
    imagen: null,
    creadoEn: '2026-06-06T10:35:00Z',
  },
];
